[package]
name = "rust_events"
version = "0.1.0"
authors = ["JP Moresmau <jp@moresmau.fr>"]
edition = "2018"


[dependencies]
serde = {version= "1.0.105", features = ["derive"]}
serde_json = "1.0.48"
rust_events_derive = { path = "../rust_events_derive" }
log = "0.4.8"
env_logger = "0.7.1"